language: r
cache: packages

install_r:
  - devtools

r_github_packages:
  - MassAtLeeds/git4research
  
script:
  # - R CMD INSTALL ../git4research/ # don't think this is needed
  - make html

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh

notifications:
  email:
    on_success: change
    on_failure: change
    